services:
  - docker
language: java
jdk:
  - openjdk8

env:
  global:
  - IMAGE_REPO=quay.io/redhatgov/openshift-tasks

cache:
  directories:
  - $HOME/.m2

before_install:
  - mkdir -p ~/.docker && echo "$AUTHFILE" | base64 -d > ~/.docker/config.json

install:
  - curl -sL -o $HOME/s2i.tar.gz https://github.com/openshift/source-to-image/releases/download/v1.3.0/source-to-image-v1.3.0-eed2850f-linux-amd64.tar.gz
  - pushd $HOME/bin && tar xvfz $HOME/s2i.tar.gz && popd

script:
  - mvn package
  - echo "$RH_PASSWORD" | docker login --username="$RH_USERNAME" --password-stdin registry.redhat.io
  - ${HOME}/bin/s2i build . registry.redhat.io/jboss-eap-7/eap73-openjdk8-openshift-rhel7 $IMAGE_REPO:$TRAVIS_BRANCH-release

deploy:
- provider: script
  script: echo "$QUAY_PASSWORD" | docker login --username="$QUAY_USERNAME" --password-stdin quay.io && docker push $IMAGE_REPO:$TRAVIS_BRANCH-release
  on:
    branch: dso4
